create table if not exists public.rps_games (
  id bigint generated by default as identity primary key,
  player_id uuid not null,
  player_choice text not null check (player_choice in ('rock','paper','scissors')),
  computer_choice text not null check (computer_choice in ('rock','paper','scissors')),
  result text not null check (result in ('win','draw','loss')),
  created_at timestamptz not null default now()
);
alter table public.rps_games enable row level security;
grant select, insert on public.rps_games to anon, authenticated;
create policy "Anyone can add game results" on public.rps_games for insert to anon, authenticated with check (true);
create policy "Anyone can view game results" on public.rps_games for select to anon, authenticated using (true);
create index if not exists rps_games_player_created_idx on public.rps_games (player_id, created_at desc);
